// flow-typed signature: 92c51356557153bf045a33c590f1a689
// flow-typed version: <<STUB>>/inferno-component_vbeta32/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-component/inferno-component' {
  declare module.exports: any;
}

declare module 'inferno-component/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-component/inferno-component.js' {
  declare module.exports: $Exports<'inferno-component/inferno-component'>;
}
declare module 'inferno-component/src/index.js' {
  declare module.exports: $Exports<'inferno-component/src/index'>;
}
