// flow-typed signature: 14bbe37d25736d1fbb33589693b5afce
// flow-typed version: <<STUB>>/redux-effects-universal-cookie_v^1.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-effects-universal-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-effects-universal-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-effects-universal-cookie/lib/index' {
  declare module.exports: any;
}

declare module 'redux-effects-universal-cookie/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-effects-universal-cookie/lib/index.js' {
  declare module.exports: $Exports<'redux-effects-universal-cookie/lib/index'>;
}
declare module 'redux-effects-universal-cookie/src/index.js' {
  declare module.exports: $Exports<'redux-effects-universal-cookie/src/index'>;
}
